### ISSUE TITLE
TypeError: Cannot read property 'number' of null

### ISSUE THREAD

**Issue by ltfschoen** [DataHighway-DHX/faucet#1]
After a few moments running the server of my faucet repository, I get the following error, and it occurs on the following line of code, so it has been commented out https://github.com/DataHighway-DHX/faucet/blob/master/helpers/contract.js#L24. That line of code isn't required for the faucet anyway: 
``
/Users/ls/code/src/DataHighway-com/faucet-mining/node_modules/@trufflesuite/web3-provider-engine/index.js:219
    number:           ethUtil.toBuffer(jsonBlock.number),
                                                 ^
TypeError: Cannot read property 'number' of null
    at toBufferBlock (/Users/ls/code/src/DataHighway-com/faucet-mining/node_modules/@trufflesuite/web3-provider-engine/index.js:219:50)
    at /Users/ls/code/src/DataHighway-com/faucet-mining/node_modules/@trufflesuite/web3-provider-engine/index.js:60:27
    at /Users/ls/code/src/DataHighway-com/faucet-mining/node_modules/@trufflesuite/web3-provider-engine/index.js:136:12
    at /Users/ls/code/src/DataHighway-com/faucet-mining/node_modules/@trufflesuite/web3-provider-engine/index.js:199:9
    at /Users/ls/code/src/DataHighway-com/faucet-mining/node_modules/async/internal/once.js:12:16
    at replenish (/Users/ls/code/src/DataHighway-com/faucet-mining/node_modules/async/internal/eachOfLimit.js:61:25)
    at /Users/ls/code/src/DataHighway-com/faucet-mining/node_modules/async/internal/eachOfLimit.js:71:9
    at eachLimit (/Users/ls/code/src/DataHighway-com/faucet-mining/node_modules/async/eachLimit.js:43:36)
    at /Users/ls/code/src/DataHighway-com/faucet-mining/node_modules/async/internal/doLimit.js:9:16
    at end (/Users/ls/code/src/DataHighway-com/faucet-mining/node_modules/@trufflesuite/web3-provider-engine/index.js:176:5)
    at /Users/ls/code/src/DataHighway-com/faucet-mining/node_modules/@trufflesuite/web3-provider-engine/subproviders/provider.js:19:5
    at XMLHttpRequest.request.onreadystatechange (/Users/ls/code/src/DataHighway-com/faucet-mining/node_modules/web3-providers-http/src/index.js:96:13)
    at XMLHttpRequestEventTarget.dispatchEvent (/Users/ls/code/src/DataHighway-com/faucet-mining/node_modules/xhr2-cookies/xml-http-request-event-target.ts:44:13)
    at XMLHttpRequest._setReadyState (/Users/ls/code/src/DataHighway-com/faucet-mining/node_modules/xhr2-cookies/xml-http-request.ts:219:8)
    at XMLHttpRequest._onHttpResponseEnd (/Users/ls/code/src/DataHighway-com/faucet-mining/node_modules/xhr2-cookies/xml-http-request.ts:345:8)
    at IncomingMessage.<anonymous> (/Users/ls/code/src/DataHighway-com/faucet-mining/node_modules/xhr2-cookies/xml-http-request.ts:311:39)`
``

See https://github.com/MetaMask/web3-provider-engine/issues/313

**Comment by sheenhx** [comment]
using parity or myetherwallet will work?

**Comment by ltfschoen** [comment]
@sheenhx I created a PR to fix the dependency here https://github.com/trufflesuite/provider-engine/pull/6

**Comment by ltfschoen** [comment]
That fix has been merged by Truffle, I've temporarily increased the version to `yarn add @truffle/hdwallet-provider@next` so we don't encounter that error which causes the whole faucet to crash.
After their weekly release cycle I'll update to the latest version 1.0.37.
