### ISSUE TITLE
DRR: TypeError: this._rpcCore.state.queryStorageAt is not a function

### ISSUE THREAD

**Issue by ltfschoen** [DataHighway-DHX/faucet#6]
When I try to request DHX from the faucet, I get the following error:

```
[0] Checking DHX token account balance of requestor
[0] Middleware to check Harbour DHX balance of requestors DataHighway address
[0] 2020-06-29T02:08:41.820Z app Balance of 0 and a nonce of 0
[0] Checking DHX token account balance of faucet
[0] Middleware to check Harbour DHX balance of faucet DataHighway address
[0] 2020-06-29T02:08:42.136Z app Balance of faucet is 999999999999998425105 and a nonce of 1
[0] 2020-06-29T02:08:42.136Z app Recipient:  5FurfdYAvwunMgCmxj7J1FKdjqETXdcBtnXVYv8cJPgb4bF9
[0] 2020-06-29T02:08:42.136Z app Sending DataHighway Harbour DHX. Please wait...
[0] 2020-06-29 04:08:42             DRR: TypeError: this._rpcCore.state.queryStorageAt is not a function
[0]     at /Users/ls/code/src/DataHighway-com/faucet-mining/node_modules/@polkadot/api/base/Decorate.js:445:228
[0]     at Array.map (<anonymous>)
[0]     at SwitchMapSubscriber.project (/Users/ls/code/src/DataHighway-com/faucet-mining/node_modules/@polkadot/api/base/Decorate.js:445:190)
[0]     at SwitchMapSubscriber._next (/Users/ls/code/src/DataHighway-com/faucet-mining/node_modules/rxjs/src/internal/operators/switchMap.ts:123:21)
[0]     at SwitchMapSubscriber.Subscriber.next (/Users/ls/code/src/DataHighway-com/faucet-mining/node_modules/rxjs/src/internal/Subscriber.ts:99:12)
[0]     at MapSubscriber._next (/Users/ls/code/src/DataHighway-com/faucet-mining/node_modules/rxjs/src/internal/operators/map.ts:89:22)
[0]     at MapSubscriber.Subscriber.next (/Users/ls/code/src/DataHighway-com/faucet-mining/node_modules/rxjs/src/internal/Subscriber.ts:99:12)
[0]     at DefaultIfEmptySubscriber._next (/Users/ls/code/src/DataHighway-com/faucet-mining/node_modules/rxjs/src/internal/operators/defaultIfEmpty.ts:75:22)
[0]     at DefaultIfEmptySubscriber.Subscriber.next (/Users/ls/code/src/DataHighway-com/faucet-mining/node_modules/rxjs/src/internal/Subscriber.ts:99:12)
[0]     at TakeLastSubscriber._complete (/Users/ls/code/src/DataHighway-com/faucet-mining/node_modules/rxjs/src/internal/operators/takeLast.ts:108:21)
[0]     at TakeLastSubscriber.Subscriber.complete (/Users/ls/code/src/DataHighway-com/faucet-mining/node_modules/rxjs/src/internal/Subscriber.ts:126:12)
[0]     at ScanSubscriber.Subscriber._complete (/Users/ls/code/src/DataHighway-com/faucet-mining/node_modules/rxjs/src/internal/Subscriber.ts:148:22)
[0]     at ScanSubscriber.Subscriber.complete (/Users/ls/code/src/DataHighway-com/faucet-mining/node_modules/rxjs/src/internal/Subscriber.ts:126:12)
[0]     at TapSubscriber._complete (/Users/ls/code/src/DataHighway-com/faucet-mining/node_modules/rxjs/src/internal/operators/tap.ts:145:29)
[0]     at TapSubscriber.Subscriber.complete (/Users/ls/code/src/DataHighway-com/faucet-mining/node_modules/rxjs/src/internal/Subscriber.ts:126:12)
[0]     at SwitchMapSubscriber.Subscriber._complete (/Users/ls/code/src/DataHighway-com/faucet-mining/node_modules/rxjs/src/internal/Subscriber.ts:148:22)
```

**Comment by ltfschoen** [comment]
See https://github.com/polkadot-js/api/issues/2398

**Comment by ltfschoen** [comment]
This is because we're using an old version of Substrate, I'm temporarily using =1.8.1 of polkadot-js/api, but will update to latest version once we've updated to latest Substrate
