### ISSUE TITLE
Unable to submit multiple requests for DHX tokens from faucet in a row

### ISSUE THREAD

**Issue by ltfschoen** [DataHighway-DHX/faucet#9]
```
[0] 2020-06-30 01:24:33        RPC-CORE: submitExtrinsic(extrinsic: Extrinsic): Hash:: 1014: Priority is too low: (3000141 vs 3000141): The transaction has too low priorit
[0] 2020-06-29T23:24:33.793Z app Error: submitExtrinsic(extrinsic: Extrinsic): Hash:: 1014: Priority is too low: (3000141 vs 3000141): The transaction has too low priorit
[0]     at CatchSubscriber.selector (/Users/ls/code/src/DataHighway-com/faucet-mining/node_modules/@polkadot/rpc-core/index.js:186:38)
[0]     at CatchSubscriber.error (/Users/ls/code/src/DataHighway-com/faucet-mining/node_modules/rxjs/src/internal/operators/catchError.ts:132:23)
[0]     at MapSubscriber.Subscriber._error (/Users/ls/code/src/DataHighway-com/faucet-mining/node_modules/rxjs/src/internal/Subscriber.ts:143:22)
[0]     at MapSubscriber.Subscriber.error (/Users/ls/code/src/DataHighway-com/faucet-mining/node_modules/rxjs/src/internal/Subscriber.ts:113:12)
[0]     at SwitchMapSubscriber.OuterSubscriber.notifyError (/Users/ls/code/src/DataHighway-com/faucet-mining/node_modules/rxjs/src/internal/OuterSubscriber.ts:17:22)
[0]     at InnerSubscriber._error (/Users/ls/code/src/DataHighway-com/faucet-mining/node_modules/rxjs/src/internal/InnerSubscriber.ts:21:17)
[0]     at InnerSubscriber.Subscriber.error (/Users/ls/code/src/DataHighway-com/faucet-mining/node_modules/rxjs/src/internal/Subscriber.ts:113:12)
[0]     at CombineLatestSubscriber.OuterSubscriber.notifyError (/Users/ls/code/src/DataHighway-com/faucet-mining/node_modules/rxjs/src/internal/OuterSubscriber.ts:17:22)
[0]     at InnerSubscriber._error (/Users/ls/code/src/DataHighway-com/faucet-mining/node_modules/rxjs/src/internal/InnerSubscriber.ts:21:17)
[0]     at InnerSubscriber.Subscriber.error (/Users/ls/code/src/DataHighway-com/faucet-mining/node_modules/rxjs/src/internal/Subscriber.ts:113:12)
[0]     at /Users/ls/code/src/DataHighway-com/faucet-mining/node_modules/rxjs/src/internal/util/subscribeToPromise.ts:12:30
[0]     at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by ltfschoen** [comment]
Possible solution here: https://matrix.to/#/!HzySYSaIhtyWrwiwEV:matrix.org/$158688662227884mNoIJ:matrix.org?via=matrix.parity.io&via=matrix.org&via=web3.foundation
